ALTER TYPE "ConversationState" ADD VALUE IF NOT EXISTS 'CHOOSING_APPOINTMENT';
ALTER TYPE "ConversationState" ADD VALUE IF NOT EXISTS 'CHOOSING_APPOINTMENT_ACTION';
ALTER TYPE "ConversationState" ADD VALUE IF NOT EXISTS 'CONFIRMING_APPOINTMENT_CANCELLATION';
