export type FinanceCategorySuggestion = {
  _id: string
  label: string
}

// Adaptado do arquivo de categorias do Glaavo para sugestao livre no financeiro.
export const CATEGORIES_EXPENSES_ARRAY: FinanceCategorySuggestion[] = [
  { _id: "alimentacao", label: "Alimentacao" },
  { _id: "assinaturasnetflixspotifyetc", label: "Assinaturas (Netflix, Spotify, etc.)" },
  { _id: "aposentadoria", label: "Aposentadoria" },
  { _id: "automoveiscomprafinanciamento", label: "Automoveis (compra, financiamento)" },
  { _id: "bancotransferenciasdepositos", label: "Banco (transferencias, depositos)" },
  { _id: "beberesairbaresrestaurantes", label: "Beber e sair (bares, restaurantes)" },
  { _id: "cartaodecredito", label: "Cartao de credito" },
  { _id: "caridade", label: "Caridade" },
  { _id: "contasapagarboletos", label: "Contas a pagar / Boletos" },
  { _id: "criancascrechebrinquedosatividades", label: "Criancas (creche, brinquedos, atividades)" },
  { _id: "compras", label: "Compras" },
  { _id: "comprasonline", label: "Compras online" },
  { _id: "cuidadospessoais", label: "Cuidados pessoais" },
  { _id: "depositodesalario", label: "Deposito de salario" },
  { _id: "despesasbancariastaxasjurosetc", label: "Despesas bancarias (taxas, juros, etc.)" },
  { _id: "dividas", label: "Dividas" },
  { _id: "doacoes", label: "Doacoes" },
  { _id: "doencasmedicamentostratamentos", label: "Doencas (medicamentos, tratamentos)" },
  { _id: "educacao", label: "Educacao" },
  { _id: "educacaofinanceira", label: "Educacao financeira" },
  { _id: "educacaosuperiorfaculdadeposgraduacao", label: "Educacao superior (faculdade, pos-graduacao)" },
  { _id: "emprestimos", label: "Emprestimos" },
  { _id: "energiaeletrica", label: "Energia eletrica" },
  { _id: "energiasolarpaineissolares", label: "Energia renovavel (paineis solares, etc.)" },
  { _id: "entretenimento", label: "Entretenimento" },
  { _id: "equipamentostecnologiagadgets", label: "Equipamentos (tecnologia, gadgets)" },
  { _id: "familiaapoiarfamiliaresaniversarios", label: "Familia (apoiar familiares, aniversarios)" },
  { _id: "freelance", label: "Freelance" },
  { _id: "futebolequipamentosingressoseventos", label: "Futebol (equipamentos, ingressos, eventos)" },
  { _id: "impostos", label: "Impostos" },
  { _id: "internet", label: "Internet" },
  { _id: "investimentos", label: "Investimentos" },
  { _id: "investimentosemacoes", label: "Investimentos em acoes" },
  { _id: "investimentosemimoveis", label: "Investimentos em imoveis" },
  { _id: "lazer", label: "Lazer" },
  { _id: "manutencaodecasapinturajardinagem", label: "Manutencao de casa (pintura, jardinagem)" },
  { _id: "microempreendedormeiiimpostos", label: "Microempreendedor (MEI, impostos)" },
  { _id: "moda", label: "Moda" },
  { _id: "moradia", label: "Moradia" },
  { _id: "outros", label: "Outros" },
  { _id: "pets", label: "Pets" },
  { _id: "previdencia", label: "Previdencia" },
  { _id: "presentes", label: "Presentes" },
  { _id: "reparosemanutencao", label: "Reparos e manutencao" },
  { _id: "restaurantesaidasrefeicoesforadecasa", label: "Restaurante (saidas, refeicoes fora de casa)" },
  { _id: "roupas", label: "Roupas" },
  { _id: "salario", label: "Salario" },
  { _id: "seguro", label: "Seguro" },
  { _id: "telefonia", label: "Telefonia" },
  { _id: "transporte", label: "Transporte" },
  { _id: "tribulacao", label: "Tribulacao" },
  { _id: "viagens", label: "Viagens" },
]

export const CATEGORIES_INCOME_ARRAY: FinanceCategorySuggestion[] = [
  { _id: "13salario", label: "13o salario" },
  { _id: "ajudasoudoacoesrecebidas", label: "Ajudas ou doacoes recebidas" },
  { _id: "aluguelrecebido", label: "Aluguel recebido" },
  { _id: "bonus", label: "Bonus" },
  { _id: "cashback", label: "Cashback" },
  { _id: "comissoes", label: "Comissoes" },
  { _id: "consultoriaseprojetos", label: "Consultorias e projetos" },
  { _id: "financiamentosrecebidos", label: "Financiamentos recebidos" },
  { _id: "freelance", label: "Freelance" },
  { _id: "horaextra", label: "Hora extra" },
  { _id: "investimentodesocios", label: "Investimento de socios" },
  { _id: "investimentosexternos", label: "Investimentos externos" },
  { _id: "jurosativos", label: "Juros ativos (juros recebidos)" },
  { _id: "licenciamentodesoftware", label: "Licenciamento de software" },
  { _id: "lucrosdeempresa", label: "Lucros de empresa" },
  { _id: "mensalidades", label: "Mensalidades" },
  { _id: "multascontratuaisrecebidas", label: "Multas contratuais recebidas" },
  { _id: "outros", label: "Outros" },
  { _id: "parceriascomerciais", label: "Parcerias comerciais" },
  { _id: "patrocinios", label: "Patrocinios" },
  { _id: "premiosouconcursos", label: "Premios ou concursos" },
  { _id: "receitadefranquia", label: "Receita de franquia" },
  { _id: "receitademanutencao", label: "Receita de manutencao" },
  { _id: "receitademarketplace", label: "Receita de marketplace" },
  { _id: "receitadepublicidade", label: "Receita de publicidade" },
  { _id: "receitadeservicos", label: "Servicos prestados" },
  { _id: "receitadevendas", label: "Receita de vendas" },
  { _id: "rendadeafiliados", label: "Renda de afiliados" },
  { _id: "rendadecursosouconsultorias", label: "Renda de cursos ou consultorias" },
  { _id: "rendimentosdeinvestimentos", label: "Rendimentos de investimentos" },
  { _id: "restituicaodeimposto", label: "Restituicao de imposto" },
  { _id: "royaltiesrecebidos", label: "Royalties recebidos" },
  { _id: "salario", label: "Salario" },
  { _id: "transferenciarecebida", label: "Transferencia recebida" },
  { _id: "vendaativosimobilizados", label: "Venda de ativos / imobilizados" },
  { _id: "vendadecursosoutreinamentos", label: "Venda de cursos ou treinamentos" },
  { _id: "vendadeprodutos", label: "Venda de produtos" },
  { _id: "vendas", label: "Vendas" },
]
